### ISSUE TITLE
'npm install' fails with "Error: Method Not Allowed"

### ISSUE THREAD

**Issue by thoughton** [TryGhost/Ghost-Vagrant#103]
I can successfully `vagrant up`, but once up I am then running into the following error during `npm install`:
```
vagrant@local:~/code/Ghost$ npm install
npm WARN deprecated nodemailer@0.7.1: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/home/vagrant/nvm/v0.10.38/lib/node_modules/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /home/vagrant/nvm/v0.10.38/lib/node_modules/npm/lib/cache/add-named.js:120:12
npm ERR!     at saved (/home/vagrant/nvm/v0.10.38/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-160-generic
npm ERR! command "/home/vagrant/nvm/v0.10.38/bin/node" "/home/vagrant/nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /home/vagrant/code/Ghost
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/code/Ghost/npm-debug.log
npm ERR! not ok code 0
```
I'm not sure if it matters, but the host system is `Ubuntu 16.04.5 LTS x86_64` running `Vagrant 2.1.5`.

**Comment by bmomartins** [comment]
I am having the same issue without vagrant, so...
