### ISSUE TITLE
Unable to load puppet

### ISSUE THREAD

**Issue by bteng22** [TryGhost/Ghost-Vagrant#86]
Having problems spinning up the vagrant box when running 'vagrant up'. Haven't used Vagrant+Puppet in a while :( Any help would be greatly appreciated!

I installed the latest versions of Vagrant (1.8.1) and VirtualBox (5.0.12 r104815). Using ruby version (2.3.0). 

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Removing hosts
==> default: Installing Puppet modules in "." with Librarian-Puppet...
Unable to load puppet. Please install it using native packages for your platform (eg .deb, .rpm, .dmg, etc).
puppet --version returned pid 6864 exit 1
/Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/defaults.rb:343: warning: duplicated key at line 344 ignored: :queue_type
/Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>': uninitialized constant Syck (NameError)
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `require'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `<module:YAML>'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:132:in `<top (required)>'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/vendor/require_vendored.rb:4:in `require'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/vendor/require_vendored.rb:4:in `<top (required)>'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/vendor.rb:38:in `require'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/vendor.rb:38:in `require_libs'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/vendor.rb:51:in `load_vendored'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:164:in `<module:Puppet>'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:29:in `<top (required)>'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/command_line.rb:12:in `require'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/command_line.rb:12:in `<top (required)>'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `require'
	from /Users/brandonteng/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `<top (required)>'
	from /Users/brandonteng/.vagrant.d/gems/bin/puppet:23:in `load'
	from /Users/brandonteng/.vagrant.d/gems/bin/puppet:23:in `<main>'
```

**Comment by bteng22** [comment]
Posting my ~/.vagrant.d/plugins.json as I'm suspecting it might have to do with librarian-puppet's version clashing with another plugin or ruby.

```
{
    "version": "1",
    "installed": {
        "vagrant-cachier": {
            "ruby_version": "2.2.3",
            "vagrant_version": "1.8.1",
            "gem_version": "",
            "require": "",
            "sources": [
                "https://rubygems.org",
                "http://gems.hashicorp.com"
            ]
        },
        "vagrant-hostsupdater": {
            "ruby_version": "2.2.3",
            "vagrant_version": "1.8.1",
            "gem_version": "",
            "require": "",
            "sources": [
                "https://rubygems.org",
                "http://gems.hashicorp.com"
            ]
        },
        "vagrant-librarian-puppet": {
            "ruby_version": "2.2.3",
            "vagrant_version": "1.8.1",
            "gem_version": "",
            "require": "",
            "sources": [
                "https://rubygems.org",
                "http://gems.hashicorp.com"
            ]
        }
    }
}
```

**Comment by mikebranski** [comment]
Yep, this was tripping me up, too. I tried on both OS X 10.11 running `ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]`, and under Windows 10 (don't have the install details handy, but can get them later if it'd be helpful). I tested against Vagrant 1.7.4 and 1.8.1, and both with, and without Puppet/Puppet Agent installed.

I haven't had time to dig further into it (just moved, then someone hit and totaled my car - good times!), but I'll look later this week if I can.

**Comment by bandrzej** [comment]
Same issue on Windows 7 x64 - Vagrant v1.8.1 w/ Virtual Box v5.0.14-105127 installed:
```
Creating vm_config.yml...
Installing the 'vagrant-cachier' plugin. This can take a few minutes...
Installed the plugin 'vagrant-cachier (1.2.1)'!
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostsupdater (1.0.2)'!
Installing the 'vagrant-librarian-puppet' plugin. This can take a few minutes...

Installed the plugin 'vagrant-librarian-puppet (0.9.1)'!
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and in
stall...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'ubuntu/trusty64' (v0) for provider: virtualbox
    default: Downloading: http://cloud-images.ubuntu.com/vagrant/trusty/current/
trusty-server-cloudimg-amd64-vagrant-disk1.box
    default: Progress: 100% (Rate: 242k/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'ubuntu/trusty64' (v0) for 'virtualbox'!
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: Ghost-Vagrant_default_1454204470732_364
65
==> default: Clearing any previously set forwarded ports...
==> default: Installing Puppet modules in "." with Librarian-Puppet...
Unable to load puppet. Please install it using native packages for your platform
 (eg .deb, .rpm, .dmg, etc).
puppet --version returned pid 3364 exit 1
C:/Users/removed/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/config.rb:47:in
 `require': cannot load such file -- win32/dir (LoadError)
        from C:/Users/removed/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/co
nfig.rb:47:in `<top (required)>'
        from C:/Users/removed/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/re
solution.rb:7:in `require'
        from C:/Users/removed/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/re
solution.rb:7:in `<top (required)>'
        from C:/Users/removed/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/fa
ct.rb:2:in `require'
        from C:/Users/removed/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/fa
ct.rb:2:in `<top (required)>'
        from C:/Users/removed/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:23:i
n `require'
        from C:/Users/removed/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:23:i
n `<module:Facter>'
        from C:/Users/removed/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:19:i
n `<top (required)>'
        from C:/Users/removed/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:6:in
 `require'
        from C:/Users/removed/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:6:in
 `<top (required)>'
        from C:/Users/removed/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/co
mmand_line.rb:12:in `require'
        from C:/Users/removed/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/co
mmand_line.rb:12:in `<top (required)>'
        from C:/Users/removed/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `r
equire'
        from C:/Users/removed/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `<
top (required)>'
        from C:/Users/removed/.vagrant.d/gems/bin/puppet:23:in `load'
        from C:/Users/removed/.vagrant.d/gems/bin/puppet:23:in `<main>'
```

Tried to install puppet for Windows as well and reran ``vagrant up`` - no dice.

**Comment by mike182uk** [comment]
@bandrzej https://ask.puppetlabs.com/question/1807/librarian-puppet-on-windows/ might solve your problem

**Comment by stringsonfire** [comment]
On Windows 10 and Vagrant 1.8.1, from within an elevated command prompt, I get the following:

```
c:\web\Ghost-Vagrant>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Installing Puppet modules in "." with Librarian-Puppet...
Unable to load puppet. Please install it using native packages for your platform (eg .deb, .rpm, .dmg, etc).
puppet --version returned pid 9756 exit 1
C:/Users/Daniel/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/config.rb:47:in `require': cannot load such file -- win32/dir (LoadError)
        from C:/Users/Daniel/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/config.rb:47:in `<top (required)>'
        from C:/Users/Daniel/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/resolution.rb:7:in `require'
        from C:/Users/Daniel/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/resolution.rb:7:in `<top (required)>'
        from C:/Users/Daniel/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/fact.rb:2:in `require'
        from C:/Users/Daniel/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/fact.rb:2:in `<top (required)>'
        from C:/Users/Daniel/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:23:in `require'
        from C:/Users/Daniel/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:23:in `<module:Facter>'
        from C:/Users/Daniel/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:19:in `<top (required)>'
        from C:/Users/Daniel/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:6:in `require'
        from C:/Users/Daniel/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:6:in `<top (required)>'
        from C:/Users/Daniel/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/command_line.rb:12:in `require'
        from C:/Users/Daniel/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/command_line.rb:12:in `<top (required)>'
        from C:/Users/Daniel/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `require'
        from C:/Users/Daniel/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `<top (required)>'
        from C:/Users/Daniel/.vagrant.d/gems/bin/puppet:23:in `load'
        from C:/Users/Daniel/.vagrant.d/gems/bin/puppet:23:in `<main>'
```

Could it be worth pursuing Issue #66?

**Comment by scottyeager** [comment]
I bumped into this too. Check out: mhahn/vagrant-librarian-puppet/issues/47. 

Puppet 3.4.3 doesn't work with newer versions of Ruby (2.0.0+, ?). The vagrant-librarian-puppet plugin hasn't been updated to use Puppet 4.x yet, but it's being [worked on](https://github.com/mhahn/vagrant-librarian-puppet/pull/49).

It's possible to manually install the plugin to get it working with Puppet 4.x (see [this comment](https://github.com/mhahn/vagrant-librarian-puppet/issues/47#issuecomment-184389820) by jhoblitt). I did this without understanding that it would cause big problems for Ghost-Vagrant, then I had a bunch of fun trying to patch it up my VM in an ssh session with no success.

This seems to signal a good time to move Ghost-Vagrant to Puppet 4.x (issue #66).

**Comment by lukewatts** [comment]
Would also be nice to have alternatives such as: 
1. A Vagrant box with a standard provisioning scripts to be able to get around problems with Puppet. I know that's way more work but at the moment this problem means a lot of people can't use this box at all.
2. A Chef provisioned version. (or Anisble)
3. A Docker container would be sweet but that's a totally other thing :)

**Comment by mike182uk** [comment]
Hm, it looks like https://github.com/mhahn/vagrant-librarian-puppet/pull/49 might resolve this so it would be worth waiting for this to land before we do anything too drastic.

In the meantime you could try using `librarian-puppet` manually, and not using the vagrant plugin (although this may have its own problems, depending on how you have ruby setup on your system):

- Uninstall the vagrant-plugin: 

```
vagrant plugin uninstall vagrant-librarian-puppet
```

- Install `librarian-puppet`:

```
gem install librarian-puppet
```

- Use `librarian-puppet` to install required dependencies:

```
librarian-puppet install
```

Running `vagrant up` should now start the VM correctly.

Another alternatively could be that we create a pre-built image (using packer and our existing puppet manifests) and use this in the Vagrantfile instead of provisioning the VM when it is started. It would be a little extra work our side, but it might make the overall user experience a little better (not to mention speed up the initial setup of the VM)? 

@lukewatts The problem here is not the provisioner, its a vagrant plugin we are using.

**Comment by stringsonfire** [comment]
vagrant-librarian-puppet 0.9.2 fixes this issue. Installed the latest version and it works fine.
